### ISSUE TITLE
Change systemd timeout times for starting and stopping apps?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/default-settings#10]
In the `/etc/systemd/system.conf` file `DefaultTimeoutStartSec` and `DefaultTimeoutStopSec` are set to 90s. It seems like this causes slow shutdowns for some people:
- https://elementaryos.stackexchange.com/questions/11202/loki-takes-long-time-to-shut-down
- https://www.linuxquestions.org/questions/blog/ztcoracat-623256/how-to-make-elementary-os-loki-and-other-ubuntu-systems-boot-faster-37621/

It's also included in the following work around list: https://elementaryos.stackexchange.com/questions/13466/elc-the-elementary-os-combobulator-a-community-project-3

People are recommending setting it to 6s for example, but then I read in the following topic that this can cause issues:
https://ubuntu-mate.community/t/regarding-defaulttimeoutstartsec-defaulttimeoutstopsec/6373/2 

Documentation from `man systemd-system.conf`:
>       DefaultTimeoutStartSec=, DefaultTimeoutStopSec=,
>       DefaultRestartSec=
>           Configures the default timeouts for starting and stopping of
>           units, as well as the default time to sleep between automatic
>           restarts of units, as configured per-unit in
>           TimeoutStartSec=, TimeoutStopSec= and RestartSec= (for
>           services, see systemd.service(5) for details on the per-unit
>           settings). For non-service units, DefaultTimeoutStartSec=
>           sets the default TimeoutSec= value.  DefaultTimeoutStartSec=
>           and DefaultTimeoutStopSec= default to 90s.
>           DefaultRestartSec= defaults to 100ms.

Maybe this isn't the appropriate repo to post this issue to, if so please let me know.

**Comment by codygarver** [comment]
I made it 25s.
