### ISSUE TITLE
Qt5 based applications like LibreOffice do not have the correct theme in Juno

### ISSUE THREAD

**Issue by Lukypie** [elementary/default-settings#116]
Probably related to https://github.com/elementary/default-settings/issues/88

Qt5 based apps like LibreOffice does not seem to follow any theme, this is the result on a plain Juno install

![Schermata da 2019-05-12 16-31-59](https://user-images.githubusercontent.com/7904559/57583766-183c3b00-74d4-11e9-858d-adb0be4c708b.png)

**Comment by danrabbit** [comment]
LibreOffice requires an additional package `libreoffice-gtk3` in order to mimic Gtk styles. There's not really anything we can do in elementary OS to enforce this, unfortunately.
