### ISSUE TITLE
Epiphany find in page close button not consistent

### ISSUE THREAD

**Issue by D0J0P** [elementary/default-settings#122]
In other apps like Code and Terminal, the Find in Page button is on the headerbar. Pressing it opens the Find in Page function, and pressing it again closes it. 

Because there's no button like this in Epiphany(which is fine), there's an x as a close button. But it's on the right instead of the left. 

The left is where the close button is for everything like windows and tabs. Maybe it should be there, or is there an even better way than that?

**Comment by peteruithoven** [comment]
This might be an issue for the Epiphany issue queue?
https://gitlab.gnome.org/GNOME/epiphany/issues

I noticed a related issue: https://gitlab.gnome.org/GNOME/epiphany/issues/4

**Comment by D0J0P** [comment]
I posted it here because I know elementary has adapted most of Epiphany to it's own HIG design, so I thought this would be within that scope.

**Comment by D0J0P** [comment]
Actually, that related issue you showed me was closed 2 months ago. Has Epiphany for eOS been updated for that change?

**Comment by peteruithoven** [comment]
I might be misunderstanding you, but that issue still seems open?
![Screenshot from 2019-07-31 09-42-32@2x](https://user-images.githubusercontent.com/523210/62193201-998ac780-b377-11e9-9614-163fb4068fe4.png)

**Comment by D0J0P** [comment]
Nevermind, I read the closed issues on that issue. Now we just have to wait until the related issue is closed. Hopefully it'll affect the find in page close button.
