### ISSUE TITLE
Manage windows in Preferences not consistent in adding/deleting buttons

### ISSUE THREAD

**Issue by D0J0P** [elementary/default-settings#123]
Adding/deleting anything of a list in elementary uses a + and - button at the bottom of the list like this: 
![Screenshot from 2019-07-26 19 13 47](https://user-images.githubusercontent.com/19495660/61985965-04d04480-afda-11e9-9ff1-214b49518db2.png)

But in a couple of places in Epiphany's Preferences, it shows up like this:

![Screenshot from 2019-07-26 19 14 00](https://user-images.githubusercontent.com/19495660/61985996-2d583e80-afda-11e9-8bb6-f90fd647a8d0.png)
Manage Search Engines under "General"

And this one is a completely different concept, adding buttons with text on the side of languages:
![Screenshot from 2019-07-26 19 19 05](https://user-images.githubusercontent.com/19495660/61986064-79a37e80-afda-11e9-8fcb-3e0e2110ee0e.png)

The Languages & Region setting in the Settings app uses the same design as the first picture above. I think this might have been taken from Gnome's Epiphany app directly.

**Comment by peteruithoven** [comment]
@D0J0P please understand that Epiphany is a "external" project. If you think they should adopt the elementary OS style of doing things you should probably open an issue in their issue queue?
https://gitlab.gnome.org/GNOME/epiphany/

Relevant: https://github.com/elementary/website/issues/2072

**Comment by D0J0P** [comment]
I understand, but there isn't a repository for Epiphany in elementary's GitHub, so people seem to be putting Epiphany issues in this repository. I posted this here because it has to do with UI.
