### ISSUE TITLE
Epiphany Keyboard Shortcuts doesn't look native to elementary

### ISSUE THREAD

**Issue by D0J0P** [elementary/default-settings#124]
The current Keyboard Shortcuts window in the menu of Epiphany doesn't look like the Keyboard Shortcuts window when pressing Super. 
![Screenshot from 2019-07-26 19 27 14](https://user-images.githubusercontent.com/19495660/61986175-647b1f80-afdb-11e9-9d6b-4253524dbcfc.png)

**Comment by peteruithoven** [comment]
@D0J0P please understand that Epiphany is a "external" project. If you think they should adopt the elementary OS style of doing things you should probably open an issue in their issue queue?
https://gitlab.gnome.org/GNOME/epiphany/
