### ISSUE TITLE
Epiphany print window not native to elementary

### ISSUE THREAD

**Issue by D0J0P** [elementary/default-settings#125]
Settings > Print
![Screenshot from 2019-07-26 20 15 50](https://user-images.githubusercontent.com/19495660/61987178-63012580-afe2-11e9-87ed-796764dc024a.png)

**Comment by peteruithoven** [comment]
Again, please stop opening these issues here. Epiphany is a external project: https://gitlab.gnome.org/GNOME/epiphany/ 

We do patch / change it with some patches, but those are managed in the os-patches repo. See:
https://github.com/elementary/os-patches/tree/epiphany-browser-bionic-patched
https://github.com/elementary/os-patches/compare/epiphany-browser-bionic...epiphany-browser-bionic-patched

Actually, why wouldn't that be the "native" print window? 
Except for it being black this is the window I get when initiating print from the Photos app:
![Screenshot from 2019-07-27 10-02-00@2x](https://user-images.githubusercontent.com/523210/61991798-c8422e80-b055-11e9-8fb0-0e82a5581012.png)
 
This is the window I get from the Document viewer (also a external project):
![Screenshot from 2019-07-27 10-04-14@2x](https://user-images.githubusercontent.com/523210/61991819-f293ec00-b055-11e9-8fff-a79d20e840c8.png)

There will always be a difference with the System Settings > Printers screen, just like there is a difference between the file selector you use in specific apps when opening files and the Files app.

**Comment by D0J0P** [comment]
It's not native because it's a piece of UI from Gnome. I know they patched Epiphany to at least look like a native first party app in elementary, and you can see the UIs aren't 100% identical. The new tab button is on the tab bar, and the tab bar is always on display. I thought I'd report this to try to have the settings/print screen go along with elementary's HIG as well.

I didn't know Photo's print screen was the same as well. I know that app was a fork of Shotwell, but I thought it's UI was fully adapted to eOS' HIG. 

The Document Viewer is Evince, a Gnome app. IMO, I think every app that comes out of the box should look fully native, and not have any Gnome bits left in them. 

Would os-patches repo be a better place to report the print screen in apps and Epiphany's settings screen?

**Comment by peteruithoven** [comment]
Yeah the patches repo would be a better place. 

Photos is currently a elementary OS specific application: https://github.com/elementary/photos/
