### ISSUE TITLE
Meson branch fails to build for missing lightdm.conf

### ISSUE THREAD

**Issue by quequotion** [elementary/default-settings#131]
Is it intended that a lightdm configuration will be shipped at some point?

meson.build [specifies the file to install](https://github.com/elementary/default-settings/blob/7a753cec8e8aa1a61152a3ab75990e55b12fbd25/meson.build#L14), but there is no such file available in the source tree.

**Comment by worldofpeace** [comment]
Same as https://github.com/elementary/default-settings/issues/132#issuecomment-522301169
It's WIP and out of date.

If you're interested in building this with Meson see https://github.com/elementary/default-settings/pull/119

**Comment by quequotion** [comment]
It's unfortunate that was allowed to happen; not sure what the hold up is; I believe it was intended that all the vala packages at least would transition to meson.

**Comment by quequotion** [comment]
Presumably resolved by #119, thanks @worldofpeace!
