### ISSUE TITLE
meson.build: org.pantheon.switchboard.dockitem or io.elementary.switchboard.dockitem?

### ISSUE THREAD

**Issue by quequotion** [elementary/default-settings#132]
meson.build is looking for [org.pantheon.switchboard.dockitem](https://github.com/elementary/default-settings/blob/7a753cec8e8aa1a61152a3ab75990e55b12fbd25/meson.build#L44), but the actual file provided is io.elementary.switchboard.dockitem.

My impression is that elementary is gradually transitioning from org.pantheon.foo to io.elementary.foo, so the latter is probably correct, although I haven't checked on switchboard's .desktop file to see if this is reflected there.

**Comment by worldofpeace** [comment]
I'd say this is invalid because that file is from a WIP branch 
* https://github.com/elementary/default-settings/tree/meson

And they've already transitioned to the correct RDDN and renamed it properly on master
* https://github.com/elementary/default-settings/commit/8da15632bc388d53d6e26ca1b3dfde8240326887

**Comment by quequotion** [comment]
As I understand it all of elementary OS's vala packages are intended to transition to meson, so rather than invalid I'd call this an issue that is holding back merging the meson branch (along with various other updates).

Rather than opening a pull request against master, we should probably update the meson branch and make a pull request against it first--unless you are confident you can get #119 to build.

**Comment by worldofpeace** [comment]
> Rather than opening a pull request against master, we should probably update the meson branch and make a pull request against it first

It had conflicts and things changed, it was better to start fresh.

> unless you are confident you can get #119 to build.

Not sure what that's in response to, perhaps you're interpreting the build status from what the CI reported? If that's so, it simply needs to be updated to accommodate the meson build system.
I've been informed to just handle that in a separate PR.

**Comment by quequotion** [comment]
Yeah, I noticed Travis CI failed, didn't look into why.

As long as the work gets done, it doesn't really matter how it gets done, and credit will go where it is due, but to be honest I find it disconcerting how the meson transition effort for this package was abandoned mid-stream.

**Comment by quequotion** [comment]
Congrats on getting #119 merged!

Just noticed today. This issue is invalidated as RDNN is complete in master.
