### ISSUE TITLE
Enable/Disable Thinner TitleBars

### ISSUE THREAD

**Issue by SephReed** [elementary/default-settings#148]
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Vertical screen real-estate is practically sacred to me.  Maybe it's a knee jerk reaction from the days of ie toolbars.  The apps in EOS do a pretty good job of not wasting it, but there's still a fair amount of padding which I'd like to able to cut down.

![Screenshot from 2019-11-10 19-11-34](https://user-images.githubusercontent.com/14002040/68549298-8cf22280-03ee-11ea-8ada-ebea630b7023.png)

**Describe the solution you'd like**

A drop down somewhere in system settings where you can reduce the top/bottom padding in these apps would be nice.  I don't know if the styling is done on a per app basis, or if they share styling... which would either make this easy or impossible.

**Existing work**

There are ways to make gnome apps waste less header space.  This should probably be included in EOS as well, because GNOME apps are horrendous without it.

https://securitronlinux.com/bejiitaswrath/how-to-make-the-title-bars-in-gnome-shell-much-thinner-than-the-default/

**Describe alternatives you've considered**

Sticking with MacOS :/ .... I'm waiting for EOS to solve some of these hyper-critical every-second-of-use aesthetic issue before I make the switch.  But I do believe in you guys.

**Additional context**

If there was a way to remove the topbar entirely in fullscreen mode, then slide it in when the mouse went to the top of the screen, that would be nice.  Just anything at all that can be done to minimize space wasted to headers that aren't currently being interacted with would be nice.  I full screen everything on MacOS and am spoiled with having zero wasted header pretty much 100% of the time I'm on my computer.

**Comment by hanaral** [comment]
Hasn't MacOS done the same thing now? The reason elementary does it is for consistency of context. i.e. The terminal has 1 button so it gets almost default size and an app or a different mode of an app gets a fatter one if it has critical widgets in the CSD. If you think that elementary's csd is too large then you might want to change your DPI settings to shrink them a little.

**Comment by SephReed** [comment]
My code sense doesn't see Changing DPI as a logical solution.   I've learned my lesson about linux hacks that end up being a lot of time and energy for something that breaks if you breathe on it.

Besides, EOS prides itself on its aesthetics a for good reason, and I think almost everybody in design agrees at this point that wasting vertical space is worth avoiding.  If nothing else, I'd like to suggest that future designs do what they can to minimize usage of vertical space (especially negative vertical space).

**Comment by danrabbit** [comment]
Headerbars are indeed already smaller than the titlebar/toolbar/menubar combo, so you're right that this is an optical illusion. You're actually already saving quite a lot of vertical space. Headerbars in elementary OS are also already about 8px smaller than the ones in GNOME.

In elementary OS 6, we now have a way to scale the UI based on your selected text size. So I'm inclined to close this as "fixed".

@cassidyjames thoughts?

**Comment by cassidyjames** [comment]
Yeah, as written this would require generating and maintaining an entire extra set of GTK stylesheets if we wanted to squeeze every pixel out of them as an option. HeaderBars are the size they are to maintain usable/grabbable size while accommodating their contents: buttons, entries, view switchers, etc. Apps can choose to use a thinner style depending on their contents as well, as seen with Terminal, Calculator, and other apps.

If the issue overall is that the UI feels too big for your display's size and resolution, we indeed support scaling the UI with the font now in Settings → Desktop → Appearance.
