### ISSUE TITLE
Screen to mount encrypted volumes is dirtier at startup

### ISSUE THREAD

**Issue by febrezo** [elementary/default-settings#16]
Not sure where to place this, but I feel that this may be the repo. After installing eOS 0.4.1 in an encrypted volume, the password request window has been changed. Previously, it was a black screen with a basic white elementary OS logo with the request to unlock the /dev/sdaX volume, but now it looks like this:

![seleccion_868](https://user-images.githubusercontent.com/1590496/34328781-1844a592-e8e9-11e7-9092-10e8d1813367.png)

I have noticed this after trying to reproduce an error when trying to mount encrypted partitions after a recent upgrade.

**Comment by btkostner** [comment]
Do you happen to have an nvidia graphics card?

**Comment by codygarver** [comment]
Probably a drivers bug, also outside the scope of this github repository so I'm closing.

**Comment by 4jNsY6fCVqZv** [comment]
@codygarver I'm just wondering: In which repository does this type of issue belong? I have a similar one.
