### ISSUE TITLE
Add Files to the Dock

### ISSUE THREAD

**Issue by cemetary** [elementary/default-settings#191]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Since Files is a core app of the OS, I think it should be present in the Dock by default.

**Describe the solution you'd like**
Add Files to the Dock.

**Comment by worldofpeace** [comment]
I believe from past discussion it's considered considered developer tooling, along with the Terminal and Code.
However, I'm also at a disposition of disagreement of this. I've yet to actually see a Linux user not know how to use a graphical file manager or need to use one regularly.

**Comment by cemetary** [comment]
Terminal, Code... I get it. But Files? Isn't Files one of the first applications regular users run after they start the OS?

**Comment by worldofpeace** [comment]
> Terminal, Code... I get it. But Files? Isn't Files one of the first applications regular users run after they start the OS?

Oh, I was "disposition of disagreement" on the past discussion. I really don't see much evil in putting into the dock. I still think running it as admin is an option, but any user can find excellent and new ways to destroy their systems quicker than we can prevent them from doing it in the first place. Only stateless systems offer more safety from user destruction, like they could wipe `/etc` bu is was going to be torn down and recreated anyways.

**Comment by hanaral** [comment]
Pretty sure you can mess things up ral quick by wiping Xsession stuff in your home. YMMV

**Comment by cassidyjames** [comment]
We intentionally don't have Files in the dock, as we encourage an app-based workflow over a file-based one.

**Comment by sryze** [comment]
@cassidyjames That makes sense on mobile, but elementaryOS is a desktop operating system, I think it's reasonable to have Files pined to the dock by default

**Comment by ChildishGiant** [comment]
> We encourage an app-based workflow over a file-based one.

I think I don't really understand what you mean by this. Interacting with files is one of the most common tasks in any desktop operating system. Even my parents use the file explorer often.

**Comment by danrabbit** [comment]
Reopening due to findings while investigating https://github.com/orgs/elementary/projects/99 and https://blog.elementary.io/2021-ui-study-results-dock-multitasking/

Specifically, as a result of a polling 96% of respondents said they use the file manager to access files and folders while 45% said they use apps
