### ISSUE TITLE
External touchpad settings aren't persistent

### ISSUE THREAD

**Issue by hanaral** [elementary/default-settings#206]
## What Happened

Using an external Bluetooth trackpad such as the Magic Trackpad results in its settings being defaulted to no natural scrolling and tap to click. I'm pretty sure @cassidyjames also commented on twitter about this. I'd also like to note that the toggles on the settings panel need to be flipped twice since for some reason their default states aren't effected by connecting/disconnecting it

## Expected Behavior

The trackpad settings have sane defaults and are persistent across reconnects on Bluetooth devices.

Also, would it not be more logical to have devices show up in the panel's side bar so that they can have their settings changed idividually? They could possibly have a toggle at the top of the device-specific settings to either just follow global or have settings for that device only (not sure how possible this is)

## Steps to Reproduce

1. Connect BT touchpad
2. Go to settings panel to see that the toggles aren't correctly set
3. Flip them to desired position
4. Reconnect device or suspend/wake computer
5. Observe the incorrect behaviour

## Platform Information

elementary OS 6 Daily

**Comment by JoseExposito** [comment]
I can confirm this happens.

**Comment by hanaral** [comment]
Don't know when it was fixed, but it's been good for a while now 👌️

**Comment by JoseExposito** [comment]
Yes, I don't know how or when it got fixed, but it's back to normal now. Upstream magic? xD
