### ISSUE TITLE
multitouch gestures two actions performed in one gesture 

### ISSUE THREAD

**Issue by fidelisakilan** [elementary/default-settings#209]
## What Happened

when i swipe left or right in touchpad two actions are triggered, both to next workspace and tile left and right is triggered.
also when swiping up with three fingers multitask view and maximize a window is triggered 
swiping with 4 fingers up or down is showing a animated arrow for the moving to next workspace.

## Expected Behaviour

Expected to move workspace with three finger swipe horizontally and multitask view when swiping upward.
Two finger gestures in moving pages in a app is working properly
## Steps to Reproduce

1.Newly installed daily ISO on a laptop(Not VM).
2.trying out gestures with touchpad.

## Platform Information

![image](https://user-images.githubusercontent.com/24905278/104796562-44e24300-57dd-11eb-940e-c2351d8b9c94.png)
![image](https://user-images.githubusercontent.com/24905278/104796564-4d3a7e00-57dd-11eb-820c-c6c39eff8858.png)
EXACT PROBLEM in a screenshot.
![Screenshot from 2021-01-16 09-29-51](https://user-images.githubusercontent.com/24905278/104796585-73f8b480-57dd-11eb-878b-390f566f790c.png)

**Comment by davidmhewitt** [comment]
FYI `/etc/skel` is just a template for newly created users, it does not affect already existing users.

**Comment by JoseExposito** [comment]
I think that `/etc/skell` could work. The config placed in `~/.config` takes precedence over `/usr`. So adding an empty config when a new user is added to their home will work.

However, I though that, on a fresh install, upstream config should be override by:
https://github.com/elementary/default-settings/blob/master/touchegg/touchegg.conf

Why did it not work?
