### ISSUE TITLE
GSettings overrides not working in installer session

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/default-settings#214]
Since #186 , the installer session doesn't have the GSettings defaults so we get the wrong icon theme/stylesheet etc.

After looking into this further, it doesn't really look like it would be possible to make it have `Pantheon` as its `XDG_CURRENT_DESKTOP` as that would cause the autostarts from the main session to start too (like the dock, and normal wingpanel, etc).

I think there's a few options:
- Revert that commit and keep overriding GNOME's stuff.
- Create/generate another set of overrides for another session name like `Pantheon-Installer`
- Make the installer a greeter and somehow figure out how that helps this situation (?)
- Ship a smaller set of overrides in the installer itself as we probably only need theme stuff

**Comment by tintou** [comment]
It also seems that XDG_CURRENT_DESKTOP is a dictionary, so I wonder how it would work with a session named Pantheon:Installer

**Comment by davidmhewitt** [comment]
Just tried that and `gnome-session` launches the autostarts for both session types (so we still get the dock and normal wingpanel etc in the installer session). But the GSettings overrides are correct.

**Comment by danrabbit** [comment]
We talked in standup about a couple things:
* Perhaps the Greeter should launch the installer or initial setup depending on if it's in the live session or not. This way we could reduce the number of sessions we need from pantheon, greeter, installer to just pantheon and greeter
* Perhaps the overrides for the greeter session are small enough to live in the greeter repo. Otherwise, maybe there's an easy way to have the overrides affect multiple specific sessions like the greeter and pantheon

**Comment by davidmhewitt** [comment]
I've spent the evening trying to get the installer to run in the greeter, like initial setup does, and it seems like it's going to be impossible to do without tinkering with stuff that we shouldn't.

The `lightdm` user isn't in the necessary groups to be able to elevate the permissions for the installer. So we need to continue to run it under the live session user which is in the `sudo` group. I'll have a think about ways in which we can use that user for both the installer and live sessions, instead of using the guest account for the live/demo session.

**Comment by danrabbit** [comment]
Closed in https://github.com/elementary/installer/pull/484
