### ISSUE TITLE
touchegg gestures is working even when touchpad is disbled under mouse is connected

### ISSUE THREAD

**Issue by fidelisakilan** [elementary/default-settings#216]
## What Happened

I had enabled the feature in mouse settings where touchpad will be disabled when mouse is connected
![image](https://user-images.githubusercontent.com/24905278/106774572-44b0c700-6668-11eb-8055-be694885c585.png)
So when i am connected to mouse touchpad is disabled and cant be used but the gestures for the multitasking is still working.
## Expected Behavior

When i am using mouse my touchpad input should be ignored both cursor movement and gesture control

## Steps to Reproduce

1.Go to settings> mouse & touchpad> 
2.ignore when mouse is connected option is enabled
3.try using toucpad for gestures

## Platform Information

![image](https://user-images.githubusercontent.com/24905278/106775264-f4863480-6668-11eb-8d26-3108b5bca2de.png)

**Comment by cassidyjames** [comment]
@JoseExposito is this something Touchégg should listen for?

**Comment by JoseExposito** [comment]
Definitely, and Gala as well.
I'll need to figure out how to check if the touchpad is disabled though, both for this and ignore while typing.

**Comment by JoseExposito** [comment]
Actually, I'm not sure if this should be handled by libinput. I need to investigate how it pointer movement gets disabled and then fix it at the appropriate level.

**Comment by JoseExposito** [comment]
I don't think this is a bug in our side, according to libinput:

> Available options are enabled (send events normally), disabled ( do not send events), disabled on external mouse (disable the device while an external mouse is plugged in).
https://wayland.freedesktop.org/libinput/doc/latest/configuration.html#send-events-mode

So, libinput should not be sending events, including multi-touch events, when the mouse is connected or while typing.

Does this also happen with the disable while typing setting? It'll be also interesting to test this with a newer libinput build before reporting upstream.
Unfortunately, my touchpad is external and this settings doesn't seem to apply, so I can not help with this.

**Comment by fidelisakilan** [comment]
> Does this also happen with the disable while typing setting? It'll be also interesting to test this with a newer libinput build before reporting upstream.

No 
when using keyboard gestures aren't triggered, that function seem to work fine. 
sorry took long to respond i didn't have my computer for a while

**Comment by JoseExposito** [comment]
> when using keyboard gestures aren't triggered, that function seem to work fine.

I believe both cases are handled by libinput.

Closing the issue as I don't think it is our bug.
