### ISSUE TITLE
Accent color /accountsservice/io.elementary.pantheon.AccountsService.xml

### ISSUE THREAD

**Issue by Radical4ever** [elementary/default-settings#227]
well when i edit the accent color on io.elementary.pantheon.AccountsService.xml and i reboot the system it doesnt work its stays as the default color and i tried everything but i just doesnt work.
pd: im using the new script that you can change the dark theme complete. if something that you can understand i can help you much (im completely new on github XD)

**Comment by cassidyjames** [comment]
This is not something a user should edit, but is an implementation detail to communicate the chosen accent color to the system for future use. To change the accent color on elementary OS 6, just use the System Settings → Desktop settings.

**Comment by Radical4ever** [comment]
oh, ok thnks for the answer i will wait for Elementary os 6 :)
