### ISSUE TITLE
Accent Colour Restored to Grape On Restart

### ISSUE THREAD

**Issue by kdwk** [elementary/default-settings#229]
No matter what I set it to, the accent colour is automatically changed to 'grape' after shutting down and booting up.

Update: it is found that this happens even when I log out and back in.

![Screenshot from 2021-05-01 07-12-40](https://user-images.githubusercontent.com/39268094/116774528-ad7fc380-aa4c-11eb-8ef4-6131bd480603.png)

**Comment by cassidyjames** [comment]
This may have been a pre-release issue where Gala and the Settings Daemon weren't in sync, but I'm unable to reproduce this now.
