### ISSUE TITLE
Flatpak config not installed to skel in Debian packaging

### ISSUE THREAD

**Issue by cassidyjames** [elementary/default-settings#244]
## What Happened

I installed an RC build of Odin, then noticed the AppCenter Flatpak remote does not exist for my user, e.g. with `flatpak remote-list`. I confirmed this on another RC install as well.

## Expected Behavior

The AppCenter Flatpak remote shows up for the user.

## Steps to Reproduce

1. Install a stable build
2. Run `flatpak remote-list`

## Platform Information

OS 6 RC1

**Comment by cassidyjames** [comment]
Confirmed in a live session:

```
$ flatpak remote-list 
Name        Options
appcenter   system
freedesktop system,filtered
```

**Comment by cassidyjames** [comment]
It looks like we need to manually include the files in the Debian packaging?

https://github.com/elementary/default-settings/blob/cd843651b3ca56114e34ef7d9b38d5bf4291cf87/debian/install#L4

**Comment by cassidyjames** [comment]
Is there a reason we're not using meson in the Debian packaging rather than manually defining files here?

**Comment by danrabbit** [comment]
We are using Meson to install the files during the build, but since this packaging describes several packages we also have to tell it which package to put which files in
