### ISSUE TITLE
.deb files should not be handled by the archive manager

### ISSUE THREAD

**Issue by fleshin** [elementary/default-settings#256]
### Problem

While downloading their favority apps, most users without advanced knowledge will go to the app site (spotify, discord, chrome, slack, you name it), will download the .deb file and double click on it. Today the .deb files are opened by the archive manager which is perplexing.  The .deb contents are presented to the user but there is nothing really usable the users can do with it. Or even worse, the users might try to extract the contents somewhere and tinker with it instead of proper package/dependencies handling__

### Proposal

The files app should associate the .deb packages with an app like Gdebi (or similar) by default. Also, a proper icon for .deb packages should be displayed and ideally confirm that the browser will do the same thing while opening the file when the download is complete.

### Prior Art (Optional)

This is the behavior when you download and double click an installer .exe file on Windows. 
This is the behavior already present on Ubuntu. That thing on macOS.

**Comment by danrabbit** [comment]
Transferred to default settings since this isn’t up to Files

**Comment by danirabbit** [comment]
Closing since we don't support sideloading apps from deb packages. The only app format we support is Flatpak. We don't ship an app other than the archive manager which handles debian packages, so that's why they open in the archive manager.
