### ISSUE TITLE
default-settings in conflict with switchboard apps on Slackware

### ISSUE THREAD

**Issue by slackernetuk** [elementary/default-settings#257]
### What Happened?

When 'default-settings' is installed some apps doesnt work, 'switchboard desktop plug' as an example.

### Steps to Reproduce

1. default-settings installed
2. switchboard desktop plug crashed
3. default-settings uninstalled 
4. switchboard desktop plug works

### Expected Behavior

switchboard desktop plug just works, when default-settings isn't installed

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
(io.elementary.switchboard:3104): GLib-GIO-ERROR **: 07:06:40.159: Settings schema 'io.elementary.settings-daemon.prefers-color-scheme' is not installed
```

**Comment by meisenzahl** [comment]
It seems that you have not installed https://github.com/elementary/settings-daemon.

**Comment by slackernetuk** [comment]
> It seems that you have not installed https://github.com/elementary/settings-daemon.

Indeed, because I was struggling to install it, because Slackware is a non-systemd system.
But, the weird thing is, without the default-settings it works fine.
