### ISSUE TITLE
No more `show-unicode-menu` key

### ISSUE THREAD

**Issue by cassidyjames** [elementary/default-settings#258]
On OS 7:

>No such key “show-unicode-menu” in schema “org.gnome.desktop.interface:Pantheon” as specified in override file “/usr/share/glib-2.0/schemas/default-settings.gschema.override”; ignoring override for this key.

**Comment by milouse** [comment]
This key has been moved as being just [an xsettings override thing](https://github.com/GNOME/gnome-settings-daemon/commit/815bae0575a84d93d65d72f0c71d9b247686bb8d)
