### ISSUE TITLE
No more `antialiasing` key

### ISSUE THREAD

**Issue by cassidyjames** [elementary/default-settings#259]
On OS 7:

>No such key “antialiasing” in schema “org.gnome.settings-daemon.plugins.xsettings:Pantheon” as specified in override file “/usr/share/glib-2.0/schemas/default-settings.gschema.override”; ignoring override for this key.

**Comment by milouse** [comment]
It seems to have been replaced by `font-antialiasing` option in `org.gnome.desktop.interface`.
