### ISSUE TITLE
adwaita-qt is no longer maintained

### ISSUE THREAD

**Issue by bobby285271** [elementary/default-settings#286]
Currently we have these lines:

https://github.com/elementary/default-settings/blob/37ef6062a8651875dd9d927c5730155c8b26e953/debian/control#L14

https://github.com/elementary/default-settings/blob/37ef6062a8651875dd9d927c5730155c8b26e953/profile.d/qt-style-override.sh#L1

The motivation of these lines are in https://github.com/elementary/default-settings/issues/88.

With a [decision](https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation) made in Fedora and https://github.com/FedoraQt/adwaita-qt/commit/0a774368916def5c9889de50f3323dec11de781e, the adwaita-qt project is no longer maintained and I don't aware of 1:1 replacement right now. In NixOS we are currently reducing the use of adwaita-qt & qgnomeplatform in desktops and might drop it when it FTBFS but I am not sure what will be the best action for Pantheon.

**Comment by danirabbit** [comment]
Yeah I personally feel like we should just drop this as well.
