### ISSUE TITLE
Set Super as the Overlay key

### ISSUE THREAD

**Issue by donadigo** [elementary/default-settings#3]
Original: https://github.com/elementary/applications-menu/issues/33.

Change the default applications menu shortcut from "Super+Space" to "Super".
This can be done by setting those two keys:

`org.gnome.mutter overlay-key` to `'Super_L'` (possibly adding `'Super_R'` also)
`org.pantheon.desktop.gala.behavior overlay-action` `'wingpanel --toggle-indicator=app-launcher'`

**Comment by forteller** [comment]
This is obviously what the users expect. elementary OS' mission is to be the best OS for most people, even non-technical users, as far as I know. These people will be confused and annoyed when Super doesn't work as expected, and they will think they have to use the mouse, never figuring out Super + space on their own.

**Comment by uncertainquark** [comment]
Having only 'Super' key to open applications menu is a good choice as it is the expected behavior for the Start Menu in Windows the users of which elementary os is targeting. It is also expected for people transitioning from Unity or GNOME, both of which are plenty. And it is easier to use.

It is important to note that there is no breakage in terms of other shortcuts so this seems like a good way to go.

**Comment by dustinleblanc** [comment]
I personally really like super + space, it matches the OSX Spotlight shortcut and I have spent far more time in that land than I have in Windows land over the past decade.

**Comment by cassidyjames** [comment]
@dustinleblanc @ajashton @aboudzakaria and anyone else not in favor of this change: if we change the setting listed, it actually retains the Super + Space shortcut as well. If they can safely coexist, I don't see a strong reason for supporting both at least for the first release where we change it to help aid the transition.

**Comment by aboudzakaria** [comment]
I don't believe it's a matter of coexistence with the super+space shortcut. For me, I have switched to super only two days now, at first I thought it's a great idea.
however, I have changed my thumbs up into down because ,in practice, considering the many other frequently used shortcuts that also includes super key (super+S, super+arrow for changing workspace and maximizing the window, super+W, super+T, ... ) you will find that the application menu starts to unintentionally and annoyingly pop up.

**Comment by ajashton** [comment]
> you will find that the application menu starts to unintentionally and annoyingly pop up.

+1. Even if it's not the default, I would really like an option to keep Super as a pure modifier key. Whenever I use GNOME I find myself accidentally in the Activities view all the time.

**Comment by dustinleblanc** [comment]
I agree, super is a modifier, it should have no command of it's own but rather be used in conjunction with another key.

**Comment by worldofpeace** [comment]
I feel this would break the shortcut paradigm elementary OS has currently. Maybe a healthy alternative would be to have a setting to switch it? But then again as @aboudzakaria found out and I have also. This causes a lot of unintentional openings. We don't want to introduce settings that can cause annoyences. If there's a way to have that not happen I would be fine sorta with Super being the default. But super in elementary OS does work as a modifier as @dustinleblanc said. Do we really need to appeal to Windows users that bad? 

This is the kind of silly stuff people argue over. Like tabs vs spaces. :100:

**Comment by cerebrix** [comment]
There are enough super only app menu distros.  Pantheon looks a lot like the mac os.  something everyone mentions when they first see it.  No version of the mac os, ever opened spotlight with just the Super key.

I think there are enough distros out there that are super key only app menu distros.  If people really want to use that.  They should go use a distro that already has it.  Right now, super + space is something that differentiates elementary and also, really attracts apple switchers that are sick of overpriced hardware and all over the place ui design.

**Comment by andbuitra** [comment]
Well you have to keep in mind that eOS's launcher is by no means Sportlight. Unless the team is planning on adding special features (and marketing them. Most people don't know you can do some things on the search box) and extending functionality through plugins, I think we should go with Super only for the sake of consistency across systems.

As it was stated before, this is default behavior on GNOME, Unity and Windows. It might not be  for MacOS but in Mac Spotlight is way more than just an app launcher.

**Comment by Nine-H** [comment]
what does this to to all of the `super + whatever` gala binds?

**Comment by alex285** [comment]
Is there is anyway to set the overlay key (eg Super_L) to open the Multitasking View (Super+s)?

**Comment by forteller** [comment]
> what does this do to all of the super + whatever gala binds?

It shouldn't do anything, I think? Opening the menu with Super should open it on release of Super without pressing anything else. So not on pressing Super down, only on release.

**Comment by cassidyjames** [comment]
That's accurate, but the rate of accidental Applications menu opens can increase significantly.

A few of us have been testing this and I personally am indifferent, but @danrabbit and some others have complained about accidental presses.

**Comment by cassidyjames** [comment]
So the plan forward is this: we'll configure the overlay key as Super. Then we can add a setting for what super on its own does to the keyboard settings, and set the default action to the shortcut overlay (which has a button to the keyboard shortcuts settings). :wink: Hopefully this can make everyone happy?

**Comment by ilinojkovic** [comment]
Sorry for reopening the issue, but it seems I'm still unable to change the shortcut to the application menu to be just the Super key. Have I understood the last comment correclty, that by default Super would open the shortcuts menu, but that it could be remapped from keyborad settings?

**Comment by caogia** [comment]
What if it set to open Multitasking View? And how to back to defaul after changed? Thank you
(I would suggest as GUI panel- i'm newbie)

**Comment by worldofpeace** [comment]
This currently can be configured from `Switchboard -> Keyboard` like:
![screenshot from 2018-11-29 10 14 46](https://user-images.githubusercontent.com/28888242/49231290-8c34cc00-f3e9-11e8-8f03-4e8d3c813895.png)
So I don't think it's possible from the UI to configure this to open Multitasking View.

**Comment by Pitometsu** [comment]
It's more [about](https://unix.stackexchange.com/a/168516/97334) compiling *Gtk* with `Primary=GDK_META_MASK`.

**Comment by aitor-gomila** [comment]
I don't think using Super for opening Applications is a good idea, but there should be a more visual way of saying "Super+Space does that" and show all the other keyboard shortcuts. I know that when you press Super the keyboards window appear, but that's confusing and most people just close it.
