### ISSUE TITLE
Styles for Qt apps

### ISSUE THREAD

**Issue by Letterus** [elementary/default-settings#317]
### Problem

One of the greatest features of elementary OS was that it had great styles for 3rd party apps as well. Qt apps just looked great and integrated better than on other systems.

Now they either seem to get the style of the underlying Flatpak runtime or no specific style at all. For me that's a real drawback.

### Proposal

Is there a way to provide a style to Qt apps installed via Flathub? I don't know.

Would it be possible to get styles back to Qt apps installed via apt? I know that's not the current strategy, but I'd highly appreciate it.

**Comment by danirabbit** [comment]
Qt style overrides were removed in https://github.com/elementary/default-settings/pull/295 since it seems the related upstream projects are no longer maintained

**Comment by Letterus** [comment]
Just for the record: I applied Kvantum and https://github.com/FedoraQt/QAdwaitaDecorations and Qt applications look quite ok now.
