### ISSUE TITLE
Add gtk setting for elementary button layout

### ISSUE THREAD

**Issue by teamcons** [elementary/default-settings#318]
### Problem

Some electron apps such as Discord, Spotify, do not follow elementaryOS default button layout.
I am not sure exactly why. However these are popular app, and people may wonder why there is a mismatch

From:
https://github.com/elementary/triage/issues/598

### Proposal

Force apps to use eOS layout with a GTK settings. This does not affect apps which have their own design, such as Steam, but create more conformity for those whose layout can be changed.
In the home folder, this also means tinkerers do not need root access to change theirs back, limit risk of breakage.

Create the following files:
```
.config/gtk-3.0/settings.ini
.config/gtk-4.0/settings.ini
```

With the following content:
```
[Settings]
gtk-decoration-layout=close:maximize
```

**Comment by teamcons** [comment]
Huh i just saw this https://github.com/elementary/default-settings/pull/305
id suggest here as default configuration at the user level

**Comment by danirabbit** [comment]
Yeah so it looks like `libgtk-3-0t64` provides a `/etc/gtk-3.0/settings.ini` but it doesn't provide a `/etc/gtk-4.0/settings.ini`

@teamcons is the gtk3 one also necessary or just the gtk4 one? I think we can provide the `gtk-3.0` one in `skel` instead maybe if it is

**Comment by teamcons** [comment]
> Yeah so it looks like `libgtk-3-0t64` provides a `/etc/gtk-3.0/settings.ini` but it doesn't provide a `/etc/gtk-4.0/settings.ini`
> 
> @teamcons is the gtk3 one also necessary or just the gtk4 one? I think we can provide the `gtk-3.0` one in `skel` instead maybe if it is

I am not sure, to be honest. Discord seems fine without. Maybe theres apps who would rely on the gtk3 settings.ini / built on an older electron ?
Maybe later down the line the same issue as for which package provides /etc/gtk-3.0/settings.ini will happen for gtk4 ?
