### ISSUE TITLE
Publicise elementary OS's fork of gnome-settings-daemon

### ISSUE THREAD

**Issue by quequotion** [elementary/default-settings#32]
This is what I have been spamming IRC about lately:
https://github.com/elementary/default-settings/blob/42c817d531961e1ff74a8b899628121d7bf82f1e/dpms/elementary-dpms-helper#L19

The only source I am aware of for the `manage-dpms-defaults` key is this patched version of G-S-D:
https://bazaar.launchpad.net/~elementary-os/elementaryos/os-patch-gnome-settings-daemon-xenial/revision/2

There are some issues here for packagers of Pantheon. The above patch on G-S-D constitutes a fork (of Canonical's fork) of 3.18.2, before [plugins were initiated individually](https://github.com/elementary/session-settings/issues/4). Given the state of the xdg autostarts and gnome .session file in the sessions-settings package, it is apparent that this is not the version of G-S-D intended for it to be used with. Without any newer version publicised, the version to package for Pantheon on other distros is in limbo: the newer .session file is no longer compatible with the older G-S-D, the original manage-dpms-defaults patch is no longer compatible with newer versions of G-S-D.

I [updated the patch](https://github.com/quequotion/pantheon-bzr-qq/blob/master/gnome-settings-daemon-elementary/manage-dpms.patch) to ship with 3.27.91-0ubuntu0~bionic1 (a prerelease version of what will ship with Ubuntu Bionic, and so theoretically elementary OS Juno), to package for ArchLinux.

**Comment by codygarver** [comment]
The patch has been ported over at elementary/os-patches@af897c5788231d4f76dd2f00aaaa533905109e0e
