### ISSUE TITLE
Open applications are not visible clearly on the default white dock

### ISSUE THREAD

**Issue by uncertainquark** [elementary/default-settings#39]
Open applications on a white dock:
![light](https://user-images.githubusercontent.com/22585732/37863521-3dff41e2-2f85-11e8-9821-19df8b16f81d.png)

Open applications on a dark dock:
![dark](https://user-images.githubusercontent.com/22585732/37863524-43e98b26-2f85-11e8-8a8b-d723a32ad900.png)

The difference is substantial and signals that visibility of the open apps need to be improved.

**Comment by danrabbit** [comment]
The plank theme is shipped in this repo. Can you open an issue there instead?

Closing for default-settings because it can't be fixed within the scope of this repo

**Comment by uncertainquark** [comment]
Done: https://github.com/elementary/stylesheet/issues/322 :)
