### ISSUE TITLE
Change plank color depending on the wallpaper too and not just panel color

### ISSUE THREAD

**Issue by uncertainquark** [elementary/default-settings#40]
In the [recent elementary blog post](https://medium.com/elementaryos/juno-progress-for-january-february-9b276042716e), it was detailed how the panel will change colors to better suit the wallpaper. The same should be done for the plank dock too (light or dark) for consistency if nothing else.

To give an example of how ugly the white dock can look on a dark wallpaper, see here:

![screenshot from 2018-03-24 16-15-17](https://user-images.githubusercontent.com/22585732/37863119-a3950bb0-2f7e-11e8-83e5-00c42fd8edf0.png)

And here's the same wallpaper on a dark plank dock:

![screenshot from 2018-03-24 16-15-05](https://user-images.githubusercontent.com/22585732/37863126-b50ab840-2f7e-11e8-8dd8-e2f57432ad97.png)

**Comment by codygarver** [comment]
I have to close this issue because this github repository is only for settings and values.

Your issue is about a dock feature request, so it belongs at https://github.com/ricotz/plank

Consider reporting this there instead.
