### ISSUE TITLE
Old Epiphany smooth scrolling key no longer used

### ISSUE THREAD

**Issue by cassidyjames** [elementary/default-settings#42]
Right now we're setting `/org/gnome/epiphany/enable-smooth-scrolling`, but apparently it has moved to `/org/gnome/epiphany/web/enable-smooth-scrolling`

_Moved from https://github.com/elementary/os/issues/69_

**Comment by danrabbit** [comment]
While we're here, I think this should be lowercase `e`. I'm not sure gsettings is case sensitive but just in case

**Comment by cassidyjames** [comment]
Ah, it appears all of our other settings are still working, but I can change that as well.
