### ISSUE TITLE
Append pantheon-filechooser-module to $GTK_MODULES

### ISSUE THREAD

**Issue by quequotion** [elementary/default-settings#47]
https://github.com/elementary/default-settings/blob/39b0a6391df04b39e2acb9f34da649ac202b3a54/profile.d/pantheon-filechooser-module.sh#L1

Just in case there are other modules, as was done with the master branch:
https://github.com/elementary/default-settings/commit/d2722d3a27e4f93e6dbd784fb1eb0eb13e1b7ba5

**Comment by codygarver** [comment]
This is already implemented, you linked to an old commit.

**Comment by quequotion** [comment]
Did I link the wrong commit? I intended to link to the 'meson' branch. This has not been fixed in that branch.

**Comment by codygarver** [comment]
The meson branch is a work in progress port of the build system from CMake to Meson that is behind in commits, only master is in use.
