### ISSUE TITLE
Inclusion of albert launcher by default

### ISSUE THREAD

**Issue by xfbs** [elementary/default-settings#64]
I would put forth a motion to include the [albert launcher](https://github.com/albertlauncher/albert) in the default installation. This is a launcher, similar to the [kupfer launcher](https://github.com/kupferlauncher/kupfer) or [gnome-do](https://do.cooperteam.net/download.shtml). All of these have been inspired by the macOS [quicksilver](https://qsapp.com/) app.

#### Why

Albert is simple, it doesn't have a lot of nuts and bolts and it is very lightweight. It can be extended with plugins, and includes some useful ones out-of-the-box. I think it fits aesthetically into elementaryOS.

![screenshot from 2018-04-27 08-08-35](https://user-images.githubusercontent.com/786420/39347317-88f35ef4-49f2-11e8-903f-18752e035455.png)

Apart from launching apps quickly, it can be used for quick calculations, to search files or open bookmarks.

#### Prior Art

Albert is more similar to macOS's current spotlight launcher than to the original QuickSilver. This is an improvement because I think the original QuickSilver interface is not the most ideal.

![](http://cdn.osxdaily.com/wp-content/uploads/2015/01/spotlight-currency-conversion-mac-os-x.jpg)

#### Downsides

Albert's current selection of plugins is okay but not great. Some of the features, such as currency conversion (which I use a lot) is missing, but that can probably be added with little effort.

Obviously, it does not make sense to clutter the default elementaryOS install with too many apps. Albert should only be included if there is demand for it.

**Comment by danrabbit** [comment]
Sorry I’m going to close this issue as “Design conflict”. elementary OS already has an app launcher and we don’t ship two of the same class of program. If you’d like to suggest features or file issues for the existing launcher you can do so here: https://github.com/elementary/applications-menu/issues
