### ISSUE TITLE
Change Default Shortcut for Minimize

### ISSUE THREAD

**Issue by ghost** [elementary/default-settings#93]
Right now 'super + w' and 'super + a' do the same thing it appears. 
And the shortcut to minimize is 'super + (the key I can't reach and already changed to make it easier)'
I would like to propose the default minimize be 'super + a' since I believe it's very easy and something people want to do a lot (minimize windows that is).

also 'super + w' makes sense for it's current function since it deals with windows.

I hope this all makes sense.. thanks.

**Comment by ryonakano** [comment]
> Right now 'super + w' and 'super + a' do the same thing it appears.

Just a note, actually their behavior is a little different. Suppose there are some window(s) opened on other workspace. Then super+w shows all windows on the current workspace. However, super+a shows all windows on the all workspace.

**Comment by 7im4pple** [comment]
Gotcha...didn't know there was a difference. I do find minimize more useful than both though.

**Comment by jlnr** [comment]
I like the current Super+H shortcut because it is consistent with both GNOME Shell and macOS, and because it's easy to remember (it __h__ides windows!).

**Comment by danirabbit** [comment]
Think I'm going to close this as "design conflict" sorry. As pointed out in a previous comment this shortcut is currently consistent with other major platforms which is pretty important for discovery
