### ISSUE TITLE
Default cursor does not scale in Juno

### ISSUE THREAD

**Issue by crouthamela** [elementary/default-settings#95]
The default cursor does not scale when using a 4k screen, leaving it very small. If I switch to another cursor theme such as Breeze, this is resolved.

**Comment by eugeneia** [comment]
Related: https://github.com/elementary/switchboard-plug-display/issues/141 https://github.com/elementary/gala/issues/300

**Comment by danirabbit** [comment]
Yeah I think this can be closed as a duplicate of https://github.com/elementary/switchboard-plug-display/issues/141
