### ISSUE TITLE
Epiphany not labeled consistently.

### ISSUE THREAD

**Issue by alexmex90** [elementary/default-settings#96]
![screenshot](https://user-images.githubusercontent.com/43529725/45937010-7cc07f00-bf71-11e8-9b69-21b53f4c7215.jpg)

Epiphany shows as GNOME Web on AppCenter and Epiphany on the launcher and the dock. It should be labeled the same in every place.

Also, Epiphany is the only one of the default applications that is not labeled accordingly to its function, it should be labeled as Web as GNOME does.

edit: I am not entirely sure if this is where this issue belongs, please move if needed.

**Comment by jlnr** [comment]
+1 for calling it just "Web". It does that in its own welcome screen already.

<img width="799" alt="bildschirmfoto 2018-09-24 um 09 05 22" src="https://user-images.githubusercontent.com/70772/45940365-00618680-bfd9-11e8-8886-55fa2832f584.png">

**Comment by alexmex90** [comment]
Epiphany is an internal codename. The application itself is called Web.

https://wiki.gnome.org/Apps/Web/

**Comment by ChildishGiant** [comment]
This should be closed with the release Odin

**Comment by danrabbit** [comment]
Yes, closing since we ship Web how it comes from upstream
